"""
UI tests for ROS optimizations display.

TERMINOLOGY NOTE:
- "Recommendations" = The raw suggestions generated by Kruize (the recommendation engine)
- "Optimizations" = How the UI presents these recommendations to users

The UI displays Kruize recommendations as "Optimizations" at:
  /openshift/cost-management/optimizations

These are the same data - just different terminology between backend (recommendations)
and frontend (optimizations). The ROS (Resource Optimization Service) processor
fetches recommendations from Kruize and stores them for the UI to display.

DATA REQUIREMENTS:
These tests work best when optimization data exists. To populate data:
1. Run e2e tests with E2E_CLEANUP_AFTER=false
2. Then run these UI tests

Without data, tests will verify empty state handling or skip gracefully.
"""

import re

import pytest
from playwright.sync_api import Page, expect


# =============================================================================
# Test Classes
# =============================================================================


@pytest.mark.ui
@pytest.mark.ros
class TestOptimizationsDisplay:
    """Test the optimizations page display.
    
    These tests check the optimizations page UI. They work with or without data:
    - If data exists (from e2e tests), they verify the table displays
    - If no data, they verify the empty state displays correctly
    """

    def test_optimizations_page_loads(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify optimizations page loads and shows either data or empty state."""
        authenticated_page.goto(f"{ui_url}/openshift/cost-management/optimizations")
        authenticated_page.wait_for_load_state("networkidle")
        
        # Page should show either a data table or empty state
        content = authenticated_page.locator(
            "table, [role='grid'], .pf-c-table, .pf-v6-c-table, "
            ".pf-c-empty-state, .pf-v6-c-empty-state, .empty-state"
        )
        expect(content.first).to_be_visible(timeout=15000)

    def test_optimizations_table_visible_when_data_exists(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify optimizations table is displayed when data exists.
        
        This test requires data to be present (run e2e tests first with E2E_CLEANUP_AFTER=false).
        """
        authenticated_page.goto(f"{ui_url}/openshift/cost-management/optimizations")
        authenticated_page.wait_for_load_state("networkidle")
        
        # Look for table or data grid component
        table_locator = authenticated_page.locator(
            "table, [role='grid'], .pf-c-table, .pf-v6-c-table"
        )
        
        # If no table found, check for empty state and skip
        if table_locator.count() == 0:
            empty_state = authenticated_page.locator(
                ".pf-c-empty-state, .pf-v6-c-empty-state, .empty-state"
            )
            if empty_state.count() > 0:
                pytest.skip("No optimization data available - run e2e tests first with E2E_CLEANUP_AFTER=false")
        
        expect(table_locator.first).to_be_visible(timeout=10000)


@pytest.mark.ui
@pytest.mark.ros
class TestOptimizationDetails:
    """Test optimization detail views.
    
    These tests require optimization data to be present. Run e2e tests first
    with E2E_CLEANUP_AFTER=false to populate the data.
    """

    def test_can_click_optimization_row(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify clicking an optimization row shows details.

        The on-prem UI may show details via URL navigation (breakdown page)
        or inline (drawer/expanded row). Both patterns are valid.
        """
        authenticated_page.goto(f"{ui_url}/openshift/cost-management/optimizations")
        authenticated_page.wait_for_load_state("networkidle")

        optimization_link = authenticated_page.locator(
            "table tbody tr a, [role='row'] a, table tbody tr[role='row']"
        ).first

        if optimization_link.count() == 0:
            pytest.skip("No optimization rows available - run e2e tests first with E2E_CLEANUP_AFTER=false")

        url_before = authenticated_page.url
        optimization_link.click()
        authenticated_page.wait_for_load_state("networkidle")

        url_changed = authenticated_page.url != url_before
        has_detail_content = authenticated_page.locator(
            "text=/cpu|memory|request|limit|container|recommendation/i"
        ).count() > 0

        assert url_changed or has_detail_content, (
            "Clicking optimization row should either navigate to a detail page "
            "or reveal detail content inline (drawer/expanded row)"
        )

    def test_optimization_page_shows_resource_info(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify optimizations page shows CPU/memory related content."""
        authenticated_page.goto(f"{ui_url}/openshift/cost-management/optimizations")
        authenticated_page.wait_for_load_state("networkidle")
        
        # Look for CPU/memory related content (case insensitive)
        resource_info = authenticated_page.locator(
            "text=/cpu|memory|cores|gib|container|pod|request|limit/i"
        )
        
        if resource_info.count() == 0:
            # Check if page has empty state instead
            empty_state = authenticated_page.locator(
                ".pf-c-empty-state, .pf-v6-c-empty-state, .empty-state"
            )
            if empty_state.count() > 0:
                pytest.skip("No optimization data - run e2e tests first with E2E_CLEANUP_AFTER=false")
            pytest.skip("No resource information visible on page")
        
        expect(resource_info.first).to_be_visible()
