"""
UI tests for ROS optimizations display.

TERMINOLOGY NOTE:
- "Recommendations" = The raw suggestions generated by Kruize (the recommendation engine)
- "Optimizations" = How the UI presents these recommendations to users

The UI displays Kruize recommendations as "Optimizations" at:
  /openshift/cost-management/optimizations

These are the same data - just different terminology between backend (recommendations)
and frontend (optimizations). The ROS (Resource Optimization Service) processor
fetches recommendations from Kruize and stores them for the UI to display.

DATA REQUIREMENTS:
These tests work best when optimization data exists. To populate data:
1. Run e2e tests with E2E_CLEANUP_AFTER=false
2. Then run these UI tests

Without data, tests will verify empty state handling or skip gracefully.
"""

import re
import time

import pytest
from playwright.sync_api import Page, expect


def get_page_content_signature(page: Page) -> str:
    """Capture a content signature to detect page state changes after a click."""
    return page.locator("body").inner_text()[:2000]


def click_first_optimization_row(page: Page) -> None:
    """Click the first optimization cluster link to drill into container view."""
    row_link = page.locator(
        "table tbody tr td a, table tbody tr a, [role='row'] a"
    ).first
    if row_link.count() > 0:
        row_link.click()
    else:
        page.locator("table tbody tr, [role='row']").first.click()
    page.wait_for_load_state("networkidle")
    time.sleep(2)


# =============================================================================
# Test Classes
# =============================================================================


@pytest.mark.ui
@pytest.mark.ros
class TestOptimizationsDisplay:
    """Test the optimizations page display.
    
    These tests check the optimizations page UI. They work with or without data:
    - If data exists (from e2e tests), they verify the table displays
    - If no data, they verify the empty state displays correctly
    """

    def test_optimizations_page_loads(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify optimizations page loads and shows either data or empty state."""
        authenticated_page.goto(f"{ui_url}/openshift/cost-management/optimizations")
        authenticated_page.wait_for_load_state("networkidle")
        
        # Page should show either a data table or empty state
        content = authenticated_page.locator(
            "table, [role='grid'], .pf-c-table, .pf-v6-c-table, "
            ".pf-c-empty-state, .pf-v6-c-empty-state, .empty-state"
        )
        expect(content.first).to_be_visible(timeout=15000)

    def test_optimizations_table_visible_when_data_exists(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify optimizations table is displayed when data exists.
        
        This test requires data to be present (run e2e tests first with E2E_CLEANUP_AFTER=false).
        """
        authenticated_page.goto(f"{ui_url}/openshift/cost-management/optimizations")
        authenticated_page.wait_for_load_state("networkidle")
        
        # Look for table or data grid component
        table_locator = authenticated_page.locator(
            "table, [role='grid'], .pf-c-table, .pf-v6-c-table"
        )
        
        # If no table found, check for empty state and skip
        if table_locator.count() == 0:
            empty_state = authenticated_page.locator(
                ".pf-c-empty-state, .pf-v6-c-empty-state, .empty-state"
            )
            if empty_state.count() > 0:
                pytest.skip("No optimization data available - run e2e tests first with E2E_CLEANUP_AFTER=false")
        
        expect(table_locator.first).to_be_visible(timeout=10000)


@pytest.mark.ui
@pytest.mark.ros
class TestOptimizationDetails:
    """Test optimization detail views.
    
    These tests require optimization data to be present. Run e2e tests first
    with E2E_CLEANUP_AFTER=false to populate the data.
    """

    def test_can_click_optimization_row(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify clicking a cluster row changes the page state.

        The on-prem UI shows cluster-level efficiency summaries. Clicking a
        cluster name applies a filter to drill into container-level data.
        """
        authenticated_page.goto(f"{ui_url}/openshift/cost-management/optimizations")
        authenticated_page.wait_for_load_state("networkidle")

        rows = authenticated_page.locator("table tbody tr, [role='row']")
        if rows.count() == 0:
            pytest.skip(
                "No optimization rows available - run e2e tests first with E2E_CLEANUP_AFTER=false"
            )

        content_before = get_page_content_signature(authenticated_page)
        url_before = authenticated_page.url

        click_first_optimization_row(authenticated_page)

        url_changed = authenticated_page.url != url_before
        content_after = get_page_content_signature(authenticated_page)
        content_changed = content_after != content_before
        has_filter_active = authenticated_page.locator(
            "text=/clear all filters/i"
        ).count() > 0

        assert url_changed or content_changed or has_filter_active, (
            "Clicking optimization row should change page state "
            "(URL change, content change, or filter applied). "
            f"url_changed={url_changed}, content_changed={content_changed}, "
            f"has_filter_active={has_filter_active}"
        )

    def test_optimization_page_shows_resource_info(
        self, authenticated_page: Page, ui_url: str
    ):
        """Verify optimizations page shows CPU/memory related content."""
        authenticated_page.goto(f"{ui_url}/openshift/cost-management/optimizations")
        authenticated_page.wait_for_load_state("networkidle")
        
        # Look for CPU/memory related content (case insensitive)
        resource_info = authenticated_page.locator(
            "text=/cpu|memory|cores|gib|container|pod|request|limit/i"
        )
        
        if resource_info.count() == 0:
            # Check if page has empty state instead
            empty_state = authenticated_page.locator(
                ".pf-c-empty-state, .pf-v6-c-empty-state, .empty-state"
            )
            if empty_state.count() > 0:
                pytest.skip("No optimization data - run e2e tests first with E2E_CLEANUP_AFTER=false")
            pytest.skip("No resource information visible on page")
        
        expect(resource_info.first).to_be_visible()
