{{- if .Values.ros.api.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cost-onprem.fullname" . }}-ros-api
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: ros-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cost-onprem.fullname" . }}-ros-api
  minReplicas: {{ .Values.ros.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ros.api.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.ros.api.autoscaling.targetCPUUtilizationPercentage }}
    {{- if .Values.ros.api.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.ros.api.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
