{{- if .Values.ros.internalAuth.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cost-onprem.fullname" . }}-ros-auth-delegator
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: ros
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ .Values.ros.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
